# Generated by Django 4.0.4 on 2022-05-15 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('ProjectID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=64)),
                ('ProjectDesc', models.CharField(max_length=512)),
                ('ProjectLeader', models.CharField(max_length=64)),
                ('LeaderEmail', models.EmailField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('JobID', models.AutoField(primary_key=True, serialize=False)),
                ('JobName', models.CharField(max_length=64)),
                ('JobDesc', models.CharField(max_length=512)),
                ('PubDate', models.DateTimeField()),
                ('ProjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBweb.projects')),
            ],
        ),
    ]
