# Generated by Django 4.0.4 on 2022-05-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBweb', '0003_alter_job_jobdesc_alter_project_projectdesc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='JobDesc',
            new_name='JobDescription',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ProjectDesc',
            new_name='ProjectDescription',
        ),
        migrations.AddField(
            model_name='job',
            name='JobCategory',
            field=models.CharField(default='', max_length=64),
        ),
    ]
