# Generated by Django 4.0.4 on 2022-05-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBweb', '0005_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='JobDescription',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectDescription',
            field=models.TextField(max_length=2048),
        ),
    ]
