# Generated by Django 4.0.4 on 2022-05-25 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBweb', '0007_alter_job_projectid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimony',
            old_name='TestimonyName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='testimony',
            old_name='TestimonyTitle',
            new_name='PersonTitle',
        ),
        migrations.RenameField(
            model_name='testimony',
            old_name='TestimonyQuote',
            new_name='Quote',
        ),
    ]
