# Generated by Django 4.0.4 on 2022-05-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBweb', '0008_rename_testimonyname_testimony_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='JobTitle',
            field=models.CharField(default='', max_length=64),
        ),
    ]
