# Generated by Django 4.0.6 on 2022-08-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBweb', '0009_job_jobtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ProjectEndDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ProjectStartDate',
            field=models.DateTimeField(null=True),
        ),
    ]
