# Generated by Django 4.0.3 on 2022-08-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBweb', '0009_job_jobtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ProjectStartDate',
            field=models.DateField(null=True),
        ),
    ]
