# Generated by Django 4.0.6 on 2022-08-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBweb', '0011_project_projectisactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='LeaderEmail',
            field=models.EmailField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectDescription',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectIsActive',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectLeader',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
