# Generated by Django 4.0.4 on 2022-08-23 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBweb', '0010_project_projectstartdate'),
        ('DBweb', '0012_alter_project_leaderemail_and_more'),
    ]

    operations = [
    ]
