# Generated by Django 4.0.4 on 2022-08-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBweb', '0013_merge_20220823_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='LeaderEmail',
            field=models.EmailField(max_length=64),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectDescription',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectLeader',
            field=models.CharField(max_length=64),
        ),
    ]
