# Generated by Django 4.0.4 on 2022-08-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBweb', '0015_project_projectisfeatured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='PubDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectEndDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectStartDate',
            field=models.DateField(null=True),
        ),
    ]
