# Generated by Django 4.0.4 on 2022-08-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBweb', '0016_alter_job_pubdate_alter_project_projectenddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='PubDate',
        ),
    ]
