# Generated by Django 4.0.4 on 2022-08-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBweb', '0017_remove_job_pubdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='JobTitle',
        ),
    ]
