# Generated by Django 4.0.3 on 2022-08-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBweb', '0018_remove_job_jobtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ProjectURL',
            field=models.CharField(default=models.CharField(max_length=64), max_length=64),
        ),
    ]
