# Generated by Django 4.1 on 2022-09-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBweb', '0022_alter_job_joburl'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ProjectImage',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='JobURL',
            field=models.CharField(default=models.CharField(max_length=64), max_length=64),
        ),
    ]
